#!/usr/bin/env python3
"""Bundle Radon into a single deployable radon.lua.

Howl (the upstream build tool) only runs *inside* ComputerCraft, so this
replicates its `require` bundle: every source module is wrapped in a function
registered in a preload table behind a small require() shim. User-editable
files (config.lua, products.lua, eventHooks.lua) are NOT bundled -- the shim
falls back to loading them from the computer's disk at runtime.
"""
import base64
import os
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "radon.lua"

# Recursively bundled source roots (all *.lua).
SRC_DIRS = ["components", "core", "fonts", "modules", "util", "Krypton"]
# Individually bundled top-level modules.
TOP_FILES = ["configDefaults.lua", "profile.lua", "DefaultLayout.lua", "CardLayout.lua"]
# Binary resources -> base64 string modules (res.<stem>).
RES_DIR = ROOT / "res"
# The entry chunk, appended verbatim and run last.
ENTRY = "radon.lua"


def module_name(rel: str) -> str:
    assert rel.endswith(".lua")
    name = rel[:-4]
    if name.endswith("/init"):
        name = name[: -len("/init")]
    return name.replace("/", ".")


def collect():
    mods = {}  # module name -> lua source returning the module
    for d in SRC_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for p in sorted(base.rglob("*.lua")):
            rel = p.relative_to(ROOT).as_posix()
            mods[module_name(rel)] = p.read_text(encoding="utf-8")
    for f in TOP_FILES:
        p = ROOT / f
        if p.exists():
            mods[module_name(f)] = p.read_text(encoding="utf-8")
    # Resources: encode .rif as base64 string modules.
    if RES_DIR.exists():
        for p in sorted(RES_DIR.glob("*.rif")):
            b64 = base64.b64encode(p.read_bytes()).decode("ascii")
            mods["res." + p.stem] = 'return "%s"\n' % b64
        for p in sorted(RES_DIR.glob("*.lua")):
            mods["res." + p.stem] = p.read_text(encoding="utf-8")
    return mods


SHIM = r"""-- Radon (Kromer-enabled) single-file bundle.
-- GENERATED by tools/bundle.py -- do not edit here; edit source and rebuild.
-- config.lua, products.lua and eventHooks.lua are loaded from disk at runtime.
local __preload, __loaded = {}, {}
local __realRequire = require
local function require(name)
    local v = __loaded[name]
    if v ~= nil then return v end
    local fn = __preload[name]
    if fn then
        v = fn()
        if v == nil then v = true end
        __loaded[name] = v
        return v
    end
    -- Fall back to user files on the computer's disk.
    if fs and shell then
        local dir = fs.getDir(shell.getRunningProgram())
        local path = fs.combine(dir, (name:gsub("%.", "/")) .. ".lua")
        if fs.exists(path) then
            local chunk, err = loadfile(path)
            if not chunk then error(err, 2) end
            v = chunk()
            if v == nil then v = true end
            __loaded[name] = v
            return v
        end
    end
    if __realRequire then return __realRequire(name) end
    error("module '" .. name .. "' not found", 2)
end
"""


def main():
    mods = collect()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = [SHIM]
    for name in sorted(mods):
        src = mods[name]
        if not src.endswith("\n"):
            src += "\n"
        parts.append('__preload[%r] = function(...)\n%send\n' % (name, src))
    # Entry chunk, verbatim, sees the local require upvalue.
    entry_src = (ROOT / ENTRY).read_text(encoding="utf-8")
    parts.append("\n-- === entry: %s ===\n" % ENTRY)
    parts.append(entry_src)
    OUT.write_text("".join(parts), encoding="utf-8")
    print("wrote %s (%d modules, %d bytes)" % (OUT, len(mods), OUT.stat().st_size))


if __name__ == "__main__":
    main()
